### ISSUE TITLE
Broken for Vesper 2 format

### ISSUE THREAD

**Issue by mbbischoff** [brianpartridge/VesperExport#1]
I tested this with a `Vesper2-Notes.sqlite3` file and received the following error:

```
Traceback (most recent call last):
  File "vesper-export.py", line 89, in <module>
    sys.exit(main())
  File "vesper-export.py", line 86, in main
    main2(options, args)
  File "vesper-export.py", line 60, in main2
    exportNotes(cursor, dest_dir, markdownify)
  File "vesper-export.py", line 18, in exportNotes
    for record in cursor.execute(query):
sqlite3.OperationalError: no such column: attachmentUniqueID
```

**Comment by brianpartridge** [comment]
Sorry for the trouble, Matt. With the the data model changes that went into Vesper 2.0 I haven't updated this script and unfortunately I don't have any plans to update it.

I originally wrote it as a way to backup my data from my phone in case it ever went for a swim, but now that there is syncing I'm less concerned about that. I'd gladly accept a fix, if someone wants to take the time to write one.  I will update the readme to document the version limitation though.

**Comment by bdesham** [comment]
@mattbischoff @brianpartridge I’ve written a similar script, [vesper2-export](https://github.com/bdesham/vesper2-export), that works with Vesper 2.x.
